
### Create article(AUTHOR)
POST http://localhost:4000/author-api/article
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zOHFQUlJ1b014RGJPWXdNZjJ1blZNYmhBcjQiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3Njk2OTY4NDUsImZ2YSI6WzAsLTFdLCJpYXQiOjE3Njk2OTY3ODUsImlzcyI6Imh0dHBzOi8vcHJvbW90ZWQtZG9lLTQ4LmNsZXJrLmFjY291bnRzLmRldiIsIm5iZiI6MTc2OTY5Njc3NSwic2lkIjoic2Vzc18zOHczUHFac2xOWDFBZ0NVOHFNRTNzZEpQenoiLCJzdHMiOiJhY3RpdmUiLCJzdWIiOiJ1c2VyXzM4dnljVHQ1ZWVYZ2RscnpRRGxrQjE1UnBNZiIsInYiOjJ9.DJNYFsTRKN4i_mmfOWvfJJnXN-Z4lgrO33DbwT8ypLJtxk9ldkHAi9E9kuMr4SKEnlGZ1eTqdr6bMHAK9JhkjjAhPhuIPivv9i6Cb_iTIGlF3reGVdBZszBDA981E1ZL6PpnoiDSWHm2o4-pJxDqpzT9bGQxmpt3Pm3HltAk1jblgjx47YFmtPQtAA8bFvscPwIZZT7oj0WjMho2it_NfHNsj7S3hGqTYZfvLLDprWQjCjI5tn99sQPVaXjYLgHbkMqpsg1oLftCZurkXvWFhiWYSVRsp3ZeEidPm2xlzjlE6kKnRZYahuH8YBhEto1PXqb9YfUZJ-ZRENx4p0SFZw
Content-Type: application/json

{
  "title": "Testing Clerk APIs without React",
  "category": "TECH",
  "content": "This article explains how to get Clerk JWT for REST clients."
}



### Read all active articles
GET http://localhost:4000/user-api/articles
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zOHFQUlJ1b014RGJPWXdNZjJ1blZNYmhBcjQiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3Njk2OTc1NjcsImZ2YSI6WzMsLTFdLCJpYXQiOjE3Njk2OTc1MDcsImlzcyI6Imh0dHBzOi8vcHJvbW90ZWQtZG9lLTQ4LmNsZXJrLmFjY291bnRzLmRldiIsIm5iZiI6MTc2OTY5NzQ5Nywic2lkIjoic2Vzc18zOHc0T240WVJPZk9OSFVFUkxleE4zMVVwMkkiLCJzdHMiOiJhY3RpdmUiLCJzdWIiOiJ1c2VyXzM4dnl4dFpYYVFBMDBtb2t5YXNDc2Y4dnFwUCIsInYiOjJ9.Mdu9ZI-3SOJgFNkJlJVIkWGb7zqn6DILB7BmNhoAoBVxzlRwHC9DnCZiPcORlVShqgwVuY_Zi9HVXL0prb56_gCRE92UGhaWwh7h3aM6m0HAEw1kjNw9i6TeXwlAVMyjyL42nh3LKHOXLoBkiiLJUP5q7hPcTOrE3Ei7vW_un54NY1FxE9F4l5NmhrZ1eroDkQNRfTr1hluACjJgN4dJnLBBl4cy4BW24O4edKD0dIhou3o7W99iok9ndqCCKswHw6tyS7J5SvNmYcSWWpBd4fmTu7IkVQstTAqzDrukgSM8JPNmW2YZf6ypop7f8uLGsw1s0s5XLGnY3QVeZCenhQ




### Add comment to an article (User)
PUT http://localhost:4000/user-api/comment/123
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zOGhpNHVEbVZCVFpJZGlZU0FWR3JVSHkyT3AiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3Njk1OTAyMzEsImZ2YSI6WzAsLTFdLCJpYXQiOjE3Njk1OTAxNzEsImlzcyI6Imh0dHBzOi8vc2V0LWtpbmdmaXNoLTgxLmNsZXJrLmFjY291bnRzLmRldiIsIm5iZiI6MTc2OTU5MDE2MSwic2lkIjoic2Vzc18zOHNaSnNZT3JrZWtZZHc3Y0lRd0piSnFZYWsiLCJzdHMiOiJhY3RpdmUiLCJzdWIiOiJ1c2VyXzM4cUphT2psdm5KcXRiR2R1ZjN0YjdwYk5UVSIsInYiOjJ9.O-3KKLBB2lWXOgXNXMA_9gCA_VnwHsIuaBqpyCmpxtWuRry-ysiSUItFF4fq5zz1ZpJKd9i4Z_G6xXZw-rFzVgUfoAflfl-VQ4EjE3NbTlIkgMdiaZrKEzRL1821RHPUi9_DmV1mW768cvis-na1zTNWfzSobS4pbARC9hzYqCHccWZMl66Wht95VhSe1008mx_er7dGZw6YBY5DR68BwaVfKV6POFiJfBzQh6uEWXMjKFVJ-bDqVtAr35uFPtlO5_xzDqwtcQv5Z2hlB-8oAvHlWrplBD9i-LRzKnVLnC46nOALqvunFRTI_eXHmvUWikizHbSkvRh2Hyg4G_8j_A
Content-Type: application/json

{
  "comment": "This article explains Clerk integration very clearly 👍"
}





### Soft Delete Article (AUTHOR only)
PUT http://localhost:5000/articles/{{articleId}}
Authorization: Bearer {{CLERK_JWT}}
Content-Type: application/json
