### Read all active articles
GET http://localhost:4000/user-api/articles
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zOGhpNHVEbVZCVFpJZGlZU0FWR3JVSHkyT3AiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3Njk1OTIzMzgsImZ2YSI6WzM1LC0xXSwiaWF0IjoxNzY5NTkyMjc4LCJpc3MiOiJodHRwczovL3NldC1raW5nZmlzaC04MS5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3Njk1OTIyNjgsInNpZCI6InNlc3NfMzhzWkpzWU9ya2VrWWR3N2NJUXdKYkpxWWFrIiwic3RzIjoiYWN0aXZlIiwic3ViIjoidXNlcl8zOHFKYU9qbHZuSnF0YkdkdWYzdGI3cGJOVFUiLCJ2IjoyfQ.lWFEulZy2YC11MgjIR5Rg7K0OL3zvgWKTeQD3xhddZQeeP9jh2JgwSpj9VTzZlkFxC33CV8jnGTieYjc7WZUd1WqFtA_RXTxFbAXBOEnqoCLjtsqIXuaIggzwV-aSycyluKg03Gmxc0w1wo0YspWU6XsDeyiGE4rbsVYKrWzkbZD6NWJ4XEj-h8rk9mR-DqwUIhU7Su9i_7p3SBv3sZStv_yu9ZDMIwuEy01GgV8iwLuE-6Ls_QQsCk82gmVEFx1t-i-QOYjmjWmmLxuEQAT94lDY59h-OT5bh0ZvKnKndRWEwFJ3tE48V4Bp3pJnt5zIOnSy1Z7LRZQK74PzH9FVg
### Add comment to an article
PUT http://localhost:4000/user-api/comment/123
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zOGhpNHVEbVZCVFpJZGlZU0FWR3JVSHkyT3AiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3Njk1OTAyMzEsImZ2YSI6WzAsLTFdLCJpYXQiOjE3Njk1OTAxNzEsImlzcyI6Imh0dHBzOi8vc2V0LWtpbmdmaXNoLTgxLmNsZXJrLmFjY291bnRzLmRldiIsIm5iZiI6MTc2OTU5MDE2MSwic2lkIjoic2Vzc18zOHNaSnNZT3JrZWtZZHc3Y0lRd0piSnFZYWsiLCJzdHMiOiJhY3RpdmUiLCJzdWIiOiJ1c2VyXzM4cUphT2psdm5KcXRiR2R1ZjN0YjdwYk5UVSIsInYiOjJ9.O-3KKLBB2lWXOgXNXMA_9gCA_VnwHsIuaBqpyCmpxtWuRry-ysiSUItFF4fq5zz1ZpJKd9i4Z_G6xXZw-rFzVgUfoAflfl-VQ4EjE3NbTlIkgMdiaZrKEzRL1821RHPUi9_DmV1mW768cvis-na1zTNWfzSobS4pbARC9hzYqCHccWZMl66Wht95VhSe1008mx_er7dGZw6YBY5DR68BwaVfKV6POFiJfBzQh6uEWXMjKFVJ-bDqVtAr35uFPtlO5_xzDqwtcQv5Z2hlB-8oAvHlWrplBD9i-LRzKnVLnC46nOALqvunFRTI_eXHmvUWikizHbSkvRh2Hyg4G_8j_A
Content-Type: application/json

{
  "comment": "This article explains Clerk integration very clearly 👍"
}




### Create article
POST http://localhost:4000/author-api/articles
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zOGhpNHVEbVZCVFpJZGlZU0FWR3JVSHkyT3AiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3Njk1OTIyMTYsImZ2YSI6WzMzLC0xXSwiaWF0IjoxNzY5NTkyMTU2LCJpc3MiOiJodHRwczovL3NldC1raW5nZmlzaC04MS5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3Njk1OTIxNDYsInNpZCI6InNlc3NfMzhzWkpzWU9ya2VrWWR3N2NJUXdKYkpxWWFrIiwic3RzIjoiYWN0aXZlIiwic3ViIjoidXNlcl8zOHFKYU9qbHZuSnF0YkdkdWYzdGI3cGJOVFUiLCJ2IjoyfQ.kuvzNtpYy58XO7j6xPTggw0ZWTXHs_9LYbub3HtpUHdEF3OiW3m4o9vrihU_jyWI2WIvHVZdYZlKWEkd491CtuEuJ2thWJBgO-23FjN_umbqV81MM67AxCUCOPz8eNNGJyN29hH-FhlKHZlRKRzN7djtbaX3dJ1aiDBBHEl8OK9KXDJqJ4hNSdYlzWSMCA3EgaIo0Fsco4Q2Igy48YBNglyJHnzukI-vFfZzI43nW1vhDT3a3-lyIcmtNJz2X6S_qfF2Vsyr08yelg92shI501JZZktUiKOuPsmCBZ2kOpkDKpgVRJ-obozNbdWvKSkJ76zG4T_Bx4hzoT3aD9NKlA
Content-Type: application/json

{
  "title": "Testing Clerk APIs without React",
  "category": "TECH",
  "content": "This article explains how to get Clerk JWT for REST clients."
}
